# Generated by Django 6.0.3 on 2026-10-08 16:14

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_demo_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='demo').exists():
        User.objects.create(
            username='demo',
            email='demo@example.com',
            password=make_password('demo123'),
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_demo_user),
    ]
