# Generated by Django 6.1.1 on 2026-10-08 16:34

from django.db import migrations
from datetime import date, timedelta
import random

def seed_demo_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Application = apps.get_model('applications', 'Application')
    
    try:
        demo_user = User.objects.get(username='demo')
    except User.DoesNotExist:
        return

    # Delete existing demo data to prevent duplicates on re-run
    Application.objects.filter(owner=demo_user).delete()

    jobs_data = [
        {"company": "Google", "position": "Frontend Engineer", "status": "INTERVIEW", "job_type": "HYBRID"},
        {"company": "Meta", "position": "React Developer", "status": "APPLIED", "job_type": "ONSITE"},
        {"company": "Netflix", "position": "Senior UI Engineer", "status": "WISHLIST", "job_type": "REMOTE"},
        {"company": "Amazon", "position": "SDE II", "status": "REJECTED", "job_type": "ONSITE"},
        {"company": "Stripe", "position": "Frontend Developer", "status": "OFFER", "job_type": "REMOTE"},
        {"company": "Vercel", "position": "Design Engineer", "status": "INTERVIEW", "job_type": "REMOTE"},
        {"company": "Apple", "position": "Software Engineer", "status": "APPLIED", "job_type": "ONSITE"},
        {"company": "Spotify", "position": "Web Engineer", "status": "WISHLIST", "job_type": "HYBRID"},
    ]

    for index, job in enumerate(jobs_data):
        Application.objects.create(
            owner=demo_user,
            company=job["company"],
            position=job["position"],
            status=job["status"],
            job_type=job["job_type"],
            applied_on=date.today() - timedelta(days=random.randint(1, 30)),
            expected_salary=random.randint(100000, 180000),
            job_link=f"https://careers.{job['company'].lower()}.com",
            notes=f"Found this interesting role at {job['company']}."
        )

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_create_demo_user'),
    ]

    operations = [
        migrations.RunPython(seed_demo_data),
    ]
